name: Deploy Docker
on:
  push:
    branches:
      - main
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Login to DockerHub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        - name: Build Docker Image
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/final-python .
        - name: Push Docker Image
          run: docker push ${{ secrets.DOCKER_USERNAME }}/final-python